# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 214c4266c1c8d5d4bb7a3b6349452b22caa3a2a7265ab19de2d42afcdfc8eccda75fd5459b509f18df76e62cee617a1bd4cc6cba4cf424fa1194f84a8c36efdb

test:
  secret_key_base: cfc65522f1536d72a575e7a05349cdc7d2e77f9a461f05c2c7692c16525661866c7e199e2813537e76e61e526692a3d8b686b90581b7180425d9466bdf8edb84

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
